#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    networks:
      - polaris_network

  polaris:
    build:
      context: .
      network: host
    ports:
      - "8181:8181"
      - "8182"
    depends_on:
      - postgres
    environment:
      AWS_REGION: us-west-1
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - credentials:/tmp/credentials/
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8182/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - polaris_network

  jupyter:
    build:
      context: .
      dockerfile: ./notebooks/Dockerfile
      network: host
    ports:
      - "8888:8888"
    depends_on:
      polaris:
        condition: service_healthy
    environment:
      AWS_REGION: us-west-2
      POLARIS_HOST: polaris
    volumes:
      - notebooks:/home/jovyan/notebooks
    networks:
      - polaris_network

volumes:
  notebooks:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./notebooks

networks:
  polaris_network:
    driver: bridge
