services:
  glue_jupyter:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
      - "4040:4040"
      - "18080:18080"
      - "8998:8998"
      - "8888:8888"
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      POLARIS_HOST: polaris
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DISABLE_SSL: true
      DATALAKE_FORMATS: iceberg
    user: glue_user
    tty: true
    stdin_open: true
    volumes:
      - ${HOME}/.aws:/home/glue_user/.aws
      - ${JUPYTER_WORKSPACE_LOCATION}:/home/glue_user/workspace/jupyter_workspace/